Repository bbonkr/next-version-proposal-action, pull requests merged in 2024-10, with the labels that each got.

#85 chore: Update dependenceies #84
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  dist/sourcemap-register.js
  package-lock.json
  package.json
Labels: dependencies

#86 feat: Remove matching of minor labels #82
  README.md
  __tests__/next-version.test.ts
  dist/index.js
  dist/index.js.map
  package-lock.json
  src/inputs.ts
  src/latest-version.ts
  src/main.ts
  src/next-version.ts
Labels: enhancement

#89 chore: Missing remove action inputs 🚀 #88
  .github/workflows/pr-completed.yml
  action.yml
Labels: HACKTOBERFEST-ACCEPTED, chore

#91 Add default values to action
  .github/workflows/create-tag.yml
  .github/workflows/verify-pr.yml
  README.md
  action.yml
Labels: enhancement

#92 chore: Check #81
  .github/workflows/check-dist.yml
  .github/workflows/create-tag.yml
  .github/workflows/pr-completed.yml
  .github/workflows/verify-pr.yml
  action.yml
Labels: chore
